name: Update WakaTime stats

on:
  # Runs at 12am UTC
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README.md with WakaTime metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          USERNAME: pititu
          SHOW_TITLE: false
          COMMIT_MESSAGE: "chore: update README.md"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"

          # TODO: enable this some day
          SHOW_SHORT_INFO: "False"
          