name: Update WakaTime stats

on:

  # Runs at 12am UTC
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  update-readme:
    name: Update README.md with WakaTime metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"

          # TODO: enable this some day
          SHOW_SHORT_INFO: "False"
          