name: Update WakaTime stats

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          USERNAME: pititu
          SHOW_TITLE: false
          COMMIT_MESSAGE: "chore: update README.md"